basedir: "analyses"
logdir: "analyses/logs"
benchmarkdir: "analyses/benchmarks"
wrapperdir: "src/wrapper"
scriptdir: "src/scripts"

# INPUTS
sampledir: "data/current/samples"
genome: "data/current/genome/genome.fa"
# OUTPUT DIRS
mappingdir: "analyses/results/mapped_reads"
sortdir: "analyses/results/mapped_reads_sorted"
vardir: "analyses/results/varcalls"

