$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  resultdir:
    type: string

  singularity:
    type: string

  samples:
    type: string

  extra:
    type: object
    properties:
      example:
        type: string

required:
  - resultdir
  - singularity
  - samples
  - extra
