$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  resultdir:
    type: string
    
  singularity:
    type: string

  samples:
    type: string

  ref:
    type: object
    properties:
      index:
        type: string
      annotation:
        type: string
    required:
      - index
      - annotation

  extra:
    type: object
    properties:
      bwa_mem:
        type: string
      samtools_sort:
        type: string
      samtools_index:
        type: string
      freebayes:
        type: string
      
 
required:
  - resultdir
  - samples
  - ref
