resultdir: analysis

# If the workflow is run with the singularity option use this image.
singularity: "docker://continuumio/miniconda3"

# INPUTS
# tab-separated 4/5 columns:
# samplename<tab>condition<tab>pairs<tab>fq1[<tab>fq2]
# pairs column is only used if diffexp: paired: below == yes
# if pairs should be used, set the same str for any "paired" samples
samples: samples.txt

# GENOME
ref:
  index: ngs-test-data/ref/genome/genome.chr21.fa
  annotation: ngs-test-data/ref/annotation.chr21.gtf
 

extra:
  bwa_mem: "-R '@RG\tID:{sample}\tSM:{sample}'"
  samtools_sort:  "-m 4G"
  samtools_index: ""
  freebayes: ""
