# DIRS
base: analysis
data: data

# OTHER
threads: 8  # general threads per job

# INPUTS
samples:
  dir: data/samples
  r1: {sample}.fastq
  #r1: {sample}_R1.fastq.gz
  r2: {sample}_R2.fastq.gz
  # tab-separated columns: samplename, condition [OTHERCOLUMS (not parsed)...]
  # only samples defined in this sheet will be considered.
  # if None: sample will be read from dir instead
  samplesheet: None

# GENOME
genome:
  dir: data/genome
  genome: genome.fa.gz
  #dir: data/GRCh38_28
  #genomeftp: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/GRCh38.primary_assembly.genome.fa.gz
  #genome: GRCh38.primary_assembly.genome.fa.gz
  #gtfftp: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/gencode.v28.primary_assembly.annotation.gtf.gz
  #gtf: gencode.v28.primary_assembly.annotation.gtf.gz

# TOOLS
# multiqc
multiqc:
  configfile: conf/multiqc-config.yaml
  # this col will be used in addtion to col1 of the samplesheet for multiqc
  # sample naming. NOT USED IF NO SAMPLESHEET IS USED
  samplesheet_col_with_names: 2  

# OUTPUT DIRS
outputs:
  mapping: mapped_reads
  sort: mapped_reads_sorted
  var: varcalls
  multiqc: multiqc
  
