base: analysis
threads: 8  # general threads per job

# INPUTS
samples:
  dir: ngs-test-data/reads
  r1: {sample}.1.fq
  r2: {sample}.2.fq
  # tab-separated columns: samplename, condition [OTHERCOLUMS (not parsed)...]
  # only samples defined in this sheet will be considered.
  # if None: sample will be read from dir instead
  #samplesheet: samples.txt
  samplesheet: None

# GENOME
genome:
  dir: ngs-test-data/ref/genome
  genome: genome.chr21.fa
  #genomeftp: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/GRCh38.primary_assembly.genome.fa.gz
  #genome: GRCh38.primary_assembly.genome.fa.gz
  #gtfftp: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/gencode.v28.primary_assembly.annotation.gtf.gz
  #gtf: gencode.v28.primary_assembly.annotation.gtf.gz

# TOOLS
# multiqc
multiqc:
  configfile: conf/multiqc-config.yaml
  # this col will be used in addtion to col1 of the samplesheet for multiqc
  # sample naming. NOT USED IF NO SAMPLESHEET IS USED
  samplesheet_col_with_names: 2  
  
